from pathlib import Path
import re
r=Path('README.md'); s=r.read_text(encoding='utf-8')
s=s.replace('- las páginas **172–177** ya poseen representación lexicográfica estructurada, pero su reconciliación exhaustiva página por página sigue pendiente;', '- la página **172** tiene sus **55 candidatos canónicos reconciliados**: 55 `article`, sin continuaciones ni candidatos estructuralmente `unresolved`; `000584` (`Relampago`) queda como falso negativo superior, R-028 queda `merged_articles`, los 15 artículos seleccionados `ALC1737-art-000584`–`000598` quedan enlazados a evidencia estructural, permanecen 41 fronteras `pending_promotion` y el censo visible sigue no exhaustivo; p.173 tiene 42 candidatos y `000599` (`Rueda`) es un comienzo superior sin frontera propia antes de L-001 (`Sabio`);\n- las páginas **173–177** ya poseen representación lexicográfica estructurada, pero su reconciliación exhaustiva página por página sigue pendiente;',1)
s=re.sub(r'en \*\*p\.171\*\* quedan 16 `pending_promotion`\. Las páginas 145–171.*?El siguiente frente geométrico es la \*\*página 172\*\*.*?\.', 'en **p.171** quedan 16 `pending_promotion`; y en **p.172** quedan 41 `pending_promotion`. Las páginas 145–172 tienen reconciliación de candidatos completa, pero sus censos visibles aún no se consideran exhaustivos. El siguiente frente geométrico es la **página 173**, con 42 candidatos canónicos —20 izquierda y 22 derecha—; la capa seleccionada comienza con `000599` (`Rueda. Buſca redonda coſa.`), comienzo superior sin frontera propia antes de L-001 (`Sabio`).', s, count=1, flags=re.S)
r.write_text(s,encoding='utf-8')
p=Path('docs/LEXICON_PROGRESS.md'); s=p.read_text(encoding='utf-8')
section='''## Página 172 — reconciliación conservadora completada\n\nP.172 contiene **55 candidatos: 27 izquierda y 28 derecha**, todos clasificados `article`. El seleccionado **`000584` (`Relampago. Beroitcme.`)** es un comienzo fresco en el borde superior sin frontera canónica propia; los otros 14 seleccionados `000585`–`000598` se alinean con candidatos propios. R-028 queda `merged_articles`: comienza `Ruido hazer el agua` y termina con una segunda unidad `Rubio`-like, que no se promociona ni se añade al censo sin ancla independiente.\n\nQuedan **41 `pending_promotion`**, no hubo promociones y el corpus sigue en **1,045 artículos**. El mínimo sustentado es **56 comienzos visibles conocidos** y no se calculan métricas por falta de censo exhaustivo. P.173 tiene **42 candidatos: 20 izquierda y 22 derecha**; `000599` (`Rueda. Buſca redonda coſa.`) es un comienzo superior sin candidato propio y L-001 comienza `Sabio`.\n\n'''
s=s.replace('## Próximo frente\n',section+'## Próximo frente\n',1)
s=re.sub(r'en p\.171, \*\*16 `pending_promotion`\*\*\. Las páginas 145–171.*?El siguiente frente geométrico es la \*\*página digital 172\*\*.*?tramo técnicamente cerrado\.', 'en p.171, **16 `pending_promotion`**; y en p.172, **41 `pending_promotion`**. Las páginas 145–172 tienen reconciliación de candidatos completa, pero no un censo visible exhaustivo.\n\nEl siguiente frente geométrico es la **página digital 173**, con **42 candidatos canónicos: 20 izquierda y 22 derecha**. La capa seleccionada comienza con `ALC1737-art-000599` (`Rueda. Buſca redonda coſa.`), comienzo superior sin frontera propia antes de L-001 (`Sabio`). Hasta que p.145 complete censo visible y promoción, el corpus sigue publicando **1,045 artículos estructurados** y **pp.133–144** como último tramo técnicamente cerrado.', s, count=1, flags=re.S)
p.write_text(s,encoding='utf-8')
