from pathlib import Path
import re

r=Path('README.md')
s=r.read_text(encoding='utf-8')
s=s.replace('- las páginas **171–177** ya poseen representación lexicográfica estructurada, pero su reconciliación exhaustiva página por página sigue pendiente;', '- la página **171** tiene sus **24 candidatos canónicos reconciliados**: 23 `article` y 1 `continuation`, sin candidatos estructuralmente `unresolved`; L-007 queda `merged_articles`, se documentan 8 falsos negativos seleccionados `000576`–`000583`, R-001 es `continuation/from_previous_column`, permanecen 16 fronteras `pending_promotion` y el censo visible sigue no exhaustivo; p.172 tiene 55 candidatos y `000584` (`Relampago`) es un comienzo superior sin frontera propia;\n- las páginas **172–177** ya poseen representación lexicográfica estructurada, pero su reconciliación exhaustiva página por página sigue pendiente;',1)
s=re.sub(r'en \*\*p\.170\*\* quedan 36 `pending_promotion`\. Las páginas 145–170.*?El siguiente frente geométrico es la \*\*página 171\*\*.*?p\.170\.', 'en **p.170** quedan 36 `pending_promotion`; y en **p.171** quedan 16 `pending_promotion`. Las páginas 145–171 tienen reconciliación de candidatos completa, pero sus censos visibles aún no se consideran exhaustivos. El siguiente frente geométrico es la **página 172**, con 55 candidatos canónicos —27 izquierda y 28 derecha—; la capa seleccionada `ALC1737-art-000584`–`000598` comienza con `Relampago. Beroitcme.`, sin frontera propia antes de L-001 (`Redaño`).', s, count=1, flags=re.S)
r.write_text(s,encoding='utf-8')

p=Path('docs/LEXICON_PROGRESS.md')
s=p.read_text(encoding='utf-8')
section='''## Página 171 — reconciliación conservadora completada\n\nP.171 contiene **24 candidatos: 7 izquierda y 17 derecha**: **23 `article`** y **1 `continuation`**. L-007 es un megagrupo `merged_articles` que inicia `000575` y concentra ocho comienzos seleccionados sin frontera propia (`000576`–`000583`); cuatro son visibles dentro del grupo y cuatro se registran conservadoramente `between_candidates`. R-001 es forma-only y queda `continuation/from_previous_column`. L-004/L-005 quedan `undersegmented`; R-003/R-017 `merged_articles`; R-015 `article/ambiguous`. No se corrige la columna declarada de los seleccionados.\n\nQuedan **16 `pending_promotion`**, no hubo promociones y el corpus sigue en **1,045 artículos**. El mínimo sustentado es **31 comienzos visibles conocidos**; no se calculan métricas por falta de censo exhaustivo. P.172 tiene **55 candidatos: 27 izquierda y 28 derecha**; `000584` (`Relampago. Beroitcme.`) es un comienzo superior sin candidato propio y L-001 comienza `Redaño`.\n\n'''
s=s.replace('## Próximo frente\n',section+'## Próximo frente\n',1)
s=re.sub(r'en p\.170, \*\*36 `pending_promotion`\*\*\. Las páginas 145–170.*?El siguiente frente geométrico es la \*\*página digital 171\*\*.*?tramo técnicamente cerrado\.', 'en p.170, **36 `pending_promotion`**; y en p.171, **16 `pending_promotion`**. Las páginas 145–171 tienen reconciliación de candidatos completa, pero no un censo visible exhaustivo.\n\nEl siguiente frente geométrico es la **página digital 172**, con **55 candidatos canónicos: 27 izquierda y 28 derecha**. La capa seleccionada contiene `ALC1737-art-000584`–`000598` y comienza con `Relampago. Beroitcme.`; ese comienzo carece de frontera propia y L-001 comienza `Redaño`. Hasta que p.145 complete censo visible y promoción, el corpus sigue publicando **1,045 artículos estructurados** y **pp.133–144** como último tramo técnicamente cerrado.', s, count=1, flags=re.S)
p.write_text(s,encoding='utf-8')
