from pathlib import Path
import re
r=Path('README.md'); s=r.read_text(encoding='utf-8')
s=s.replace('- las páginas **173–177** ya poseen representación lexicográfica estructurada, pero su reconciliación exhaustiva página por página sigue pendiente;', '- la página **173** tiene sus **42 candidatos canónicos reconciliados**: 40 `article` y 2 `continuation`, sin candidatos estructuralmente `unresolved`; se documentan 4 falsos negativos seleccionados (`000599` Rueda, `000600` Saber generalmente, `000605` Sahumar, `000607` Salitral), L-010/L-011/R-015 quedan `merged_articles`, R-018 `undersegmented`, permanecen 29 fronteras `pending_promotion` y el censo visible sigue no exhaustivo; p.174 tiene 48 candidatos y `000614` (`Si, adv. para afirmar`) es un comienzo superior sin frontera propia antes de L-001 (`Si, conj.`);\n- las páginas **174–177** ya poseen representación lexicográfica estructurada, pero su reconciliación exhaustiva página por página sigue pendiente;',1)
s=re.sub(r'en \*\*p\.172\*\* quedan 41 `pending_promotion`\. Las páginas 145–172.*?El siguiente frente geométrico es la \*\*página 173\*\*.*?\.', 'en **p.172** quedan 41 `pending_promotion`; y en **p.173** quedan 29 `pending_promotion`. Las páginas 145–173 tienen reconciliación de candidatos completa, pero sus censos visibles aún no se consideran exhaustivos. El siguiente frente geométrico es la **página 174**, con 48 candidatos canónicos —26 izquierda y 22 derecha—; la capa seleccionada comienza con `000614` (`Si, adv. para afirmar. Hebui.`), comienzo superior sin frontera propia antes de L-001 (`Si, conj. Soc.`).', s, count=1, flags=re.S)
r.write_text(s,encoding='utf-8')
p=Path('docs/LEXICON_PROGRESS.md'); s=p.read_text(encoding='utf-8')
section='''## Página 173 — reconciliación conservadora completada\n\nP.173 contiene **42 candidatos: 20 izquierda y 22 derecha**: **40 `article`** y **2 `continuation`**. Los missed-starts seleccionados demostrados son `000599` (`Rueda`) y `000600` (`Saber generalmente`) en el borde superior, `000605` (`Sahumar`) dentro de L-010 y `000607` (`Salitral`) dentro de L-011. L-001→L-002 y R-002→R-003 son las dos continuidades. L-010, L-011 y R-015 quedan `merged_articles`; R-018 queda `undersegmented`.\n\nQuedan **29 `pending_promotion`**, no hubo promociones y el corpus sigue en **1,045 artículos**. El mínimo sustentado es **44 comienzos visibles conocidos** y no se calculan métricas por falta de censo exhaustivo. P.174 tiene **48 candidatos: 26 izquierda y 22 derecha**; `000614` (`Si, adv. para afirmar. Hebui.`) es un comienzo superior sin candidato propio y L-001 comienza `Si, conj. Soc.`.\n\n'''
s=s.replace('## Próximo frente\n',section+'## Próximo frente\n',1)
s=re.sub(r'en p\.172, \*\*41 `pending_promotion`\*\*\. Las páginas 145–172.*?El siguiente frente geométrico es la \*\*página digital 173\*\*.*?tramo técnicamente cerrado\.', 'en p.172, **41 `pending_promotion`**; y en p.173, **29 `pending_promotion`**. Las páginas 145–173 tienen reconciliación de candidatos completa, pero no un censo visible exhaustivo.\n\nEl siguiente frente geométrico es la **página digital 174**, con **48 candidatos canónicos: 26 izquierda y 22 derecha**. La capa seleccionada comienza con `ALC1737-art-000614` (`Si, adv. para afirmar. Hebui.`), comienzo superior sin frontera propia antes de L-001 (`Si, conj. Soc.`). Hasta que p.145 complete censo visible y promoción, el corpus sigue publicando **1,045 artículos estructurados** y **pp.133–144** como último tramo técnicamente cerrado.', s, count=1, flags=re.S)
p.write_text(s,encoding='utf-8')
